services:
  backend:
    build:
      context: backend
    ports:
      - 8081:8081
    expose:
      - 8081
    volumes:
      - type: bind
        source: backend/patientsDb.mv.db
        target: /app/patientsDb.mv.db

  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: frontend/src
        target: /code/src